server:
  port: 8004
spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/lifecapsule3
    #    url: jdbc:postgresql://pgm-8psc6119ll3w80043o.pgsql.kualalumpur.rds.aliyuncs.com:5432/lifecapsule3
#    url: jdbc:postgresql://pgm-2vc85ouuoz41kx5fco.pgsql.cn-chengdu.rds.aliyuncs.com:5432/redemption
    url: jdbc:postgresql://181.215.246.126:5432/redemption
#    url: jdbc:postgresql://localhost:5432/redemption
#    username: gogoyangsoft
    username: postgres
    #    username: icesnakeyang
    password: 112233ccddEE
#    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: logs/redemption.log